# Append New String In The Middle Of A Given String...
# Taking input the first string...
s = str(input("Enter a string: "))

# Taking input a new string...
n = str(input("Enter a new string: "))

# Middle index value of the first string...
middle_first_index = len(s)//2

# Printing The New String...
print(s[0:(middle_first_index - 1)] + n + s[middle_first_index:])
